export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOG_OUT = "LOG_OUT";
export const LOGIN_START = "LOGINT_START";
export const DEFAULT_SESSION = "DEFAULT_SESSION";

export const GET_CLIENTE = "GET_CLIENTE";
export const GET_CLIENTES = "GET_CLIENTES";
export const POST_CLIENTE = "POST_CLIENTE";
export const DELETE_CLIENTE = "DELETE_CLIENTE";
export const UPDATE_CLIENTE = "UPDATE_CLIENTE";
export const CLIENTE_ERROR = "CLIENTE_ERROR";

export const GET_PROVEEDORES = "GET_PROVEEDORES";
export const GET_PROVEEDOR = "GET_PROVEEDOR";
export const POST_PROVEEDOR = "POST_PROVEEDOR";
export const UPDATE_PROVEEDOR = "UPDATE_PROVEEDOR";
export const DELETE_PROVEEDOR = "DELETE_PROVEEDOR";
export const PROVEEDOR_ERROR = "PROVEEDOR_ERROR";

export const GET_USUARIO = "GET_USUARIO";
export const GET_USUARIOS = "GET_USUARIOS";
export const POST_USUARIO = "POST_USUARIO";
export const DELETE_USUARIO = "DELETE_USUARIO";
export const UPDATE_USUARIO = "UPDATE_USUARIO";
export const USUARIO_ERROR = "USUARIO_ERROR";
